### ISSUE TITLE
bob.ip.base should depend on vlfeat

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.conda#4]
This is not the case presently, which means our SIFT extensions will not get compiled.

**Comment by 183amir** [comment]
Not all packages were successfully built.
You can see the ones that succeeded here
https://anaconda.org/amir183/packages

**Comment by anjos** [comment]
Thanks. I created an organization in anaconda.org called `bobpkgs`. I have made you an Owner of this organization. Could you please upload/keep packages in that organization channel instead?

Thanks a lot, A

**Comment by 183amir** [comment]
This is fixed now.
