### ISSUE TITLE
Possible incorrect installation instructions

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.conda#9]
Hi,

I'm not familiarized with conda, but I think the command in the item 3 of the README is incorrect
I think the command should be  ```$ conda config --add channels jakirkham``` instead of  ```$ conda config --add config jakirkham```

**Comment by 183amir** [comment]
You are right. Could you change it please?

**Comment by tiagofrepereira2012** [comment]
Done with the commit 18897df
